export const electronics = [
    {
        id: 1,
        name: 'Samsung A50 (Metallic White, 8GB Ram, 128GB Storage)',
        price: '₹21,890',
        uri: 'https://bronze.qa/wp-content/uploads/2019/04/samsung-galaxy-a50-128-gb-white-4.jpeg',
        color1: 'orange',
        color2: 'orange',
        color3: 'orange',
        color4: 'orange',
        color5:'white',
        note: 'FREE DELIVERY'
    },
    {
        id: 2,
        name: 'Iphone 12 (128GB) - Pacific Blue & White',
        price: '₹1,05,980',
        uri: 'https://i0.wp.com/www.chooseyourmobile.com/wp-content/uploads/2018/09/iPhone-XS-Max-2.jpg?fit=1280%2C853&ssl=1',
        color1: 'orange',
        color2: 'orange',
        color3: 'orange',
        color4: 'orange',
        color5:'orange',
        note: 'FREE DELIVERY'
    },
    {
        id: 3,
        name: 'Redmi Note 9 pro (White, 6GB Ram, 64GB Storage)',
        price: '₹17,499',
        uri: 'https://geniusmobile.lk/wp-content/uploads/2020/03/Redmi-Note-9-Pro-Genius-Mobile.png',
        color1: 'orange',
        color2: 'orange',
        color3: 'orange',
        color4: 'orange',
        color5:'white',
        note: 'FREE DELIVERY'
    },
    {
        id: 4,
        name: 'Oppo F15 pro (Metallic White, 6GB Ram, 64GB Storage)',
        price: '₹21,490',
        uri: 'https://fdn2.gsmarena.com/vv/pics/oppo/oppo-f15-cph2001-1.jpg',
        color1: 'orange',
        color2: 'orange',
        color3: 'orange',
        color4: 'orange',
        color5:'orange',
        note: 'FREE DELIVERY'
    },
    {
        id: 5,
        name: 'Samsung Galaxy M51 (Celestial Black, 6GB RAM, 128GB Storage)',
        price: '₹ 22,999',
        uri: 'https://th.bing.com/th/id/OIP.ewvHIagXAp1Mi54pUjIvowHaIi?pid=ImgDet&rs=1',
        color1: 'orange',
        color2: 'orange',
        color3: 'orange',
        color4: 'orange',
        color5:'white',
        note: 'FREE DELIVERY'
    },
    {
        id: 6,
        name: 'Samsung A50 (Metallic White, 8GB Ram, 128GB Storage)',
        price: '₹21,890',
        uri: 'https://bronze.qa/wp-content/uploads/2019/04/samsung-galaxy-a50-128-gb-white-4.jpeg',
        color1: 'orange',
        color2: 'orange',
        color3: 'orange',
        color4: 'orange',
        color5:'white',
        note: 'FREE DELIVERY'
    },
    {
        id: 7,
        name: 'Iphone 12 (128GB) - Pacific Blue & White',
        price: '₹1,05,980',
        uri: 'https://i0.wp.com/www.chooseyourmobile.com/wp-content/uploads/2018/09/iPhone-XS-Max-2.jpg?fit=1280%2C853&ssl=1',
        color1: 'orange',
        color2: 'orange',
        color3: 'orange',
        color4: 'orange',
        color5:'orange',
        note: 'FREE DELIVERY'
    },
    {
        id: 8,
        name: 'Redmi Note 9 pro (White, 6GB Ram, 64GB Storage)',
        price: '₹17,499',
        uri: 'https://geniusmobile.lk/wp-content/uploads/2020/03/Redmi-Note-9-Pro-Genius-Mobile.png',
        color1: 'orange',
        color2: 'orange',
        color3: 'orange',
        color4: 'orange',
        color5:'white',
        note: 'FREE DELIVERY'
    },
    {
        id: 9,
        name: 'Oppo F15 pro (Metallic White, 6GB Ram, 64GB Storage)',
        price: '₹21,490',
        uri: 'https://fdn2.gsmarena.com/vv/pics/oppo/oppo-f15-cph2001-1.jpg',
        color1: 'orange',
        color2: 'orange',
        color3: 'orange',
        color4: 'orange',
        color5:'orange',
        note: 'FREE DELIVERY'
    },
    {
        id: 10,
        name: 'Samsung Galaxy M51 (Celestial Black, 6GB RAM, 128GB Storage)',
        price: '₹ 22,999',
        uri: 'https://th.bing.com/th/id/OIP.ewvHIagXAp1Mi54pUjIvowHaIi?pid=ImgDet&rs=1',
        color1: 'orange',
        color2: 'orange',
        color3: 'orange',
        color4: 'orange',
        color5:'white',
        note: 'FREE DELIVERY'
    },
]

export const books = [
    {
        id: 0,
        name: 'The Story of My Experiments with Trut',
        price: '₹ 799',
        uri: 'https://images-na.ssl-images-amazon.com/images/I/51qNCJg7WNL._SY346_.jpg',
        color1: 'orange',
        color2: 'orange',
        color3: 'orange',
        color4: 'orange',
        color5:'white',
        note: 'FREE DELIVERY'
    },
    {
        id: 1,
        name: 'The Theory of Everything: The Origin and Fate of the Universe',
        price: '₹ 899',
        uri: 'https://images-na.ssl-images-amazon.com/images/I/51oHUvYzbsL._SX327_BO1,204,203,200_.jpg',
        color1: 'orange',
        color2: 'orange',
        color3: 'orange',
        color4: 'orange',
        color5:'white',
        note: 'FREE DELIVERY'
    },
    {
        id: 2,
        name: 'Far From The Madding Crowd',
        price: '₹ 675',
        uri: 'https://th.bing.com/th/id/OIP.DAZPcMeplPfr5z4YRoAjYgHaMP?pid=ImgDet&rs=1',
        color1: 'orange',
        color2: 'orange',
        color3: 'orange',
        color4: 'orange',
        color5:'white',
        note: 'FREE DELIVERY'
    },
    {
        id: 3,
        name: 'Think & Grow Rich ',
        price: '₹ 599',
        uri: 'https://images-na.ssl-images-amazon.com/images/I/41KFjXZ-s+L._SX319_BO1,204,203,200_.jpg',
        color1: 'orange',
        color2: 'orange',
        color3: 'orange',
        color4: 'orange',
        color5:'white',
        note: 'FREE DELIVERY'
    },
    {
        id: 4,
        name: 'The Gaurdians Honour',
        price: '₹ 425',
        uri: 'https://th.bing.com/th/id/R9823deb25a14962232400c6ed990d0ee?rik=HRTzIfvmUJR%2bbg&riu=http%3a%2f%2fprodimage.images-bn.com%2fpimages%2f9780369704054_p0_v1_s1200x630.jpg&ehk=Ye%2bPwULuDtRVor6anfOV8ojiJ62tOajtbV3AZv%2bKy%2fw%3d&risl=&pid=ImgRaw',
        color1: 'orange',
        color2: 'orange',
        color3: 'orange',
        color4: 'orange',
        color5:'white',
        note: 'FREE DELIVERY'
    },
    {
        id: 5,
        name: 'The Theory of Everything: The Origin and Fate of the Universe',
        price: '₹ 899',
        uri: 'https://images-na.ssl-images-amazon.com/images/I/51oHUvYzbsL._SX327_BO1,204,203,200_.jpg',
        color1: 'orange',
        color2: 'orange',
        color3: 'orange',
        color4: 'orange',
        color5:'white',
        note: 'FREE DELIVERY'
    },
    {
        id: 6,
        name: 'Far From The Madding Crowd',
        price: '₹ 675',
        uri: 'https://th.bing.com/th/id/OIP.DAZPcMeplPfr5z4YRoAjYgHaMP?pid=ImgDet&rs=1',
        color1: 'orange',
        color2: 'orange',
        color3: 'orange',
        color4: 'orange',
        color5:'white',
        note: 'FREE DELIVERY'
    },
    {
        id: 7,
        name: 'Think & Grow Rich ',
        price: '₹ 825',
        uri: 'https://images-na.ssl-images-amazon.com/images/I/41KFjXZ-s+L._SX319_BO1,204,203,200_.jpg',
        color1: 'orange',
        color2: 'orange',
        color3: 'orange',
        color4: 'orange',
        color5:'white',
        note: 'FREE DELIVERY'
    },
    {
        id: 8,
        name: 'The Gaurdians Honour',
        price: '₹ 675',
        uri: 'https://th.bing.com/th/id/R9823deb25a14962232400c6ed990d0ee?rik=HRTzIfvmUJR%2bbg&riu=http%3a%2f%2fprodimage.images-bn.com%2fpimages%2f9780369704054_p0_v1_s1200x630.jpg&ehk=Ye%2bPwULuDtRVor6anfOV8ojiJ62tOajtbV3AZv%2bKy%2fw%3d&risl=&pid=ImgRaw',
        color1: 'orange',
        color2: 'orange',
        color3: 'orange',
        color4: 'orange',
        color5:'white',
        note: 'FREE DELIVERY'
    },
]